# Numpy (–ß–∞—Å—Ç—å 3)


> üöÄ –í —ç—Ç–æ–π –ø—Ä–∞–∫—Ç–∏–∫–µ –Ω–∞–º –ø–æ–Ω–∞–¥–æ–±—è—Ç—Å—è: `numpy==1.21.2`

> üöÄ –£—Å—Ç–∞–Ω–æ–≤–∏—Ç—å –≤—ã –∏—Ö –º–æ–∂–µ—Ç–µ —Å –ø–æ–º–æ—â—å—é –∫–æ–º–∞–Ω–¥—ã: `%pip install numpy==1.21.2`


## –°–æ–¥–µ—Ä–∂–∞–Ω–∏–µ

* [Broadcasting (—Ç—Ä–∞–Ω—Å–ª—è—Ü–∏—è)](#Broadcasting-—Ç—Ä–∞–Ω—Å–ª—è—Ü–∏—è)
* [–ò–∑–º–µ–Ω–µ–Ω–∏–µ —Ä–∞–∑–º–µ—Ä–æ–≤ –º–∞—Å—Å–∏–≤–∞ (Reshape)](#–ò–∑–º–µ–Ω–µ–Ω–∏–µ-—Ä–∞–∑–º–µ—Ä–æ–≤-–º–∞—Å—Å–∏–≤–∞-Reshape)
* [–û–±—ä–µ–¥–∏–Ω–µ–Ω–∏–µ –º–∞—Å—Å–∏–≤–æ–≤](#–û–±—ä–µ–¥–∏–Ω–µ–Ω–∏–µ-–º–∞—Å—Å–∏–≤–æ–≤)
  * [–ó–∞–¥–∞–Ω–∏–µ - –æ–±—ä–µ–¥–∏–Ω—è–µ–º](#–ó–∞–¥–∞–Ω–∏–µ---–æ–±—ä–µ–¥–∏–Ω—è–µ–º)
  * [–ó–∞–¥–∞–Ω–∏–µ - —Ä–∞—Å—à–∏—Ä—è–µ–º](#–ó–∞–¥–∞–Ω–∏–µ---—Ä–∞—Å—à–∏—Ä—è–µ–º)
* [–°–æ—Ä—Ç–∏—Ä–æ–≤–∫–∞ –º–∞—Å—Å–∏–≤–∞](#–°–æ—Ä—Ç–∏—Ä–æ–≤–∫–∞-–º–∞—Å—Å–∏–≤–∞)
  * [–ó–∞–¥–∞–Ω–∏–µ - –ø–æ–∫–æ–ø–∞–µ–º—Å—è –≤ –¥–æ–∫–∞—Ö](#–ó–∞–¥–∞–Ω–∏–µ---–ø–æ–∫–æ–ø–∞–µ–º—Å—è-–≤-–¥–æ–∫–∞—Ö)
  * [–ó–∞–¥–∞–Ω–∏–µ - –Ω–∏–∫—É–¥–∞ –±–µ–∑ —Å–æ—Ä—Ç–∏—Ä–æ–≤–∫–∏](#–ó–∞–¥–∞–Ω–∏–µ---–Ω–∏–∫—É–¥–∞-–±–µ–∑-—Å–æ—Ä—Ç–∏—Ä–æ–≤–∫–∏)
* [–ó–∞–¥–∞—á–∫–∏](#–ó–∞–¥–∞—á–∫–∏)
* [–ü–æ–ª–µ–∑–Ω—ã–µ —Å—Å—ã–ª–∫–∏](#–ü–æ–ª–µ–∑–Ω—ã–µ-—Å—Å—ã–ª–∫–∏)


–í —ç—Ç–æ–º –Ω–æ—É—Ç–±—É–∫–µ:
- Broadcasting - –æ–ø–µ—Ä–∞—Ü–∏–∏ –º–µ–∂–¥—É –º–∞—Å—Å–∏–≤–∞–º–∏ –Ω–µ–æ–¥–∏–Ω–∞–∫–æ–≤—ã—Ö —Ä–∞–∑–º–µ—Ä–æ–≤
- –ò–∑–º–µ–Ω–µ–Ω–∏–µ —Ñ–æ—Ä–º—ã –º–∞—Å—Å–∏–≤–∞  - reshape
- –û–±—ä–µ–¥–∏–Ω–µ–Ω–∏–µ –º–∞—Å—Å–∏–≤–æ–≤ - concatenate
- –°–æ—Ä—Ç–∏—Ä–æ–≤–∫–∞ –ø–æ —ç–ª–µ–º–µ–Ω—Ç–∞–º –∏ –∏–Ω–¥–µ–∫—Å–∞–º - sort, argsort

–¢–µ–ø–µ—Ä—å —Ä–∞—Å—Å–º–æ—Ç—Ä–∏–º –Ω–µ–∫–æ—Ç–æ—Ä—ã–µ "—Ä—É—Ç–∏–Ω–Ω—ã–µ" –ø—Ä–æ—Ü–µ–¥—É—Ä—ã —Ä–∞–±–æ—Ç—ã —Å –º–∞—Å—Å–∏–≤–∞–º–∏, –∫–æ—Ç–æ—Ä—ã–µ –ø—Ä–∏–≥–æ–¥—è—Ç—Å—è –≤ –¥–∞–ª—å–Ω–µ–π—à–µ–º. –ó–∞ –±–æ–ª–µ–µ –ø–æ–ª–Ω–æ–π –¥–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏–µ–π —Å—é–¥–∞ https://numpy.org/doc/stable/reference/routines.array-manipulation.html

In [ ]:
import numpy as np

## Broadcasting (—Ç—Ä–∞–Ω—Å–ª—è—Ü–∏—è)

Broadcasting - —ç—Ç–æ –º–µ—Ö–∞–Ω–∏–∑–º  –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è –º–∞—Ç–µ–º–∞—Ç–∏—á–µ—Å–∫–∏—Ö –æ–ø–µ—Ä–∞—Ü–∏–π —Å –º–∞—Å—Å–∏–≤–∞–º–∏ *–Ω–µ–æ–¥–∏–Ω–∞–∫–æ–≤—ã—Ö* —Ä–∞–∑–º–µ—Ä–æ–≤. –¢–µ–º–∞ –¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ "—à–∏—Ä–æ–∫–∞—è" =)

–ù–∞ –¥–µ–ª–µ –º–µ—Ö–∞–Ω–∏–∑–º –æ—á–µ–Ω—å –ø–æ–ª–µ–∑–µ–Ω –∏ –µ–≥–æ –ø–æ–Ω—è—Ç—å –µ–≥–æ —Å—Ç–æ–∏—Ç, —Ç–∞–∫ –∫–∞–∫ –æ–Ω —è–≤–ª—è–µ—Ç—Å—è –æ–¥–Ω–∏–º –∏–∑ –º–æ—â–Ω—ã—Ö –∏–Ω—Å—Ç—Ä—É–º–µ–Ω—Ç–æ–≤ –±–∏–±–ª–∏–æ—Ç–µ–∫–∏ numpy. –î–æ–ø—É—Å—Ç–∏–º, –º—ã –∏–º–µ–µ—Ç –≤–µ–∫—Ç–æ—Ä $(4,)$, –º–∞—Ç—Ä–∏—Ü—É $(3, 4)$ –∏ —Ö–æ—Ç–∏–º —É–º–Ω–æ–∂–∏—Ç—å —ç—Ç–æ—Ç –≤–µ–∫—Ç–æ—Ä –Ω–∞ –∫–∞–∂–¥—É—é —Å—Ç—Ä–æ–∫—É –º–∞—Ç—Ä–∏—Ü—ã. –°–∞–º—ã–π –ø—Ä–æ—Å—Ç–æ–π —Å–ø–æ—Å–æ–± - –ø—Ä–æ–π—Ç–∏ –≤ —Ü–∏–∫–ª–µ –ø–æ —Å—Ç—Ä–æ–∫–∞–º:

In [ ]:
vec = np.arange(4)
mtrx = np.ones((3, 4))
print(vec)
print(mtrx)

[0 1 2 3]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
result = np.empty_like(mtrx)

for i_row in range(mtrx.shape[0]):
    result[i_row,:] = mtrx[i_row,:] * vec

print(result)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


–° –¥—Ä—É–≥–æ–π —Å—Ç–æ—Ä–æ–Ω—ã, –º–æ–∂–Ω–æ —Å–∫–ª–æ–Ω–∏—Ä–æ–≤–∞—Ç—å –≤–µ–∫—Ç–æ—Ä –ø–æ —Ä–∞–∑–º–µ—Ä—É –º–∞—Ç—Ä–∏—Ü—ã, —á—Ç–æ–±—ã –∑–∞—Ç–µ–º –ø—Ä–æ—Å—Ç–æ –ø–µ—Ä–µ–º–Ω–æ–∂–∏—Ç—å –ø–æ—ç–ª–µ–º–µ–Ω—Ç–Ω–æ –¥–≤–µ –º–∞—Ç—Ä–∏—Ü—ã.

In [ ]:
# –§—É–Ω–∫—Ü–∏—è np.tile() –ø–æ–≤—Ç–æ—Ä—è–µ—Ç –º–∞—Å—Å–∏–≤ —Ç–æ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Ä–∞–∑ –∏ –ø–æ —Ç–µ–º –æ—Å—è–º,
#   –∫–æ—Ç–æ—Ä—ã–µ –∑–∞–¥–∞–Ω—ã –≤ –∞—Ä–≥—É–º–µ–Ω—Ç–µ reps
vec_m = np.tile(vec, reps=(3, 1))
print(vec_m)
print(vec_m * mtrx)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


–ê –º–æ–∂–Ω–æ –≤—Å–ø–æ–º–Ω–∏—Ç—å –ø—Ä–æ –±—Ä–æ–∞–¥–∫–∞—Å—Ç–∏–Ω–≥ –∏ –ø—Ä–æ—Å—Ç–æ —É–º–Ω–æ–∂–∏—Ç—å –≤–µ–∫—Ç–æ—Ä –Ω–∞ –º–∞—Ç—Ä–∏—Ü—É:

In [ ]:
# –£–º–Ω–æ–∂–µ–Ω–∏–µ, –∏—Å–ø–æ–ª—å–∑—É—è –±—Ä–æ–∞–¥–∫–∞—Å—Ç–∏–Ω–≥
print(vec * mtrx)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


–¢–∞–∫–∏–º –æ–±—Ä–∞–∑–æ–º, –±—Ä–æ–∞–¥–∫–∞—Å—Ç–∏–Ω–≥ - —ç—Ç–æ –º–µ—Ö–∞–Ω–∏–∑–º —Ä–∞—Å–ø—Ä–æ—Å—Ç—Ä–∞–Ω–µ–Ω–∏—è —ç–ª–µ–º–µ–Ω—Ç–æ–≤ –æ–ø–µ—Ä–∞—Ü–∏–π –ø–æ —Ä–∞–∑–º–µ—Ç–Ω–æ—Å—Ç—è–º, –ø–æ –∫–æ—Ç–æ—Ä—ã–º –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —ç–ª–µ–º–µ–Ω—Ç–æ–≤ –Ω–µ —Å–æ–æ—Ç–Ω–æ—Å–∏—Ç—Å—è —Å –¥—Ä—É–≥–∏–º –æ–ø–µ—Ä–∞–Ω–¥–æ–º. –í –ø–æ—Å–ª–µ–¥–Ω–µ–π —è—á–µ–π–∫–µ –≤–µ–∫—Ç–æ—Ä –±—ã–ª –ø—Ä–æ–¥—É–±–ª–∏—Ä–æ–≤–∞–Ω –Ω–∞ –∫–∞–∂–¥—É—é —Å—Ç—Ä–æ–∫—É —Ç–∞–∫, —á—Ç–æ —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç–∏ —Å–æ–æ—Ç–Ω–æ—Å—è—Ç—Å—è.

> –û–±—è–∑–∞—Ç–µ–ª—å–Ω–æ –ø—Ä–æ—á–∏—Ç–∞–π—Ç–µ –ø—Ä–∏–º–µ—Ä—ã –±—Ä–æ–∞–¥–∫–∞—Å—Ç–∏–Ω–≥–∞ –≤ [—Å—Ç–∞—Ç—å–µ](https://numpy.org/doc/stable/user/basics.broadcasting.html).

–ë—Ä–æ–∞–¥–∫–∞—Å—Ç–∏–Ω–≥ —Ç–∞–∫–∂–µ —Ä–∞–±–æ—Ç–∞–µ—Ç –∏ –ø—Ä–∏ —É–º–Ω–æ–∂–µ–Ω–∏–∏ —Å–∫–∞–ª—è—Ä–∞ –Ω–∞ –º–∞—Å—Å–∏–≤:

In [ ]:
print(2 * mtrx)

–ß—Ç–æ–±—ã –±–æ–ª—å—à–µ –ø–æ–Ω—è—Ç—å –ø—Ä–∞–≤–∏–ª–∞ –±—Ä–æ–∞–¥–∫–∞—Å—Ç–∏–Ω–≥–∞, –ø–æ—Å–º–æ—Ç—Ä–∏–º –Ω–∞ —Ä–µ–∑—É–ª—å—Ç–∞—Ç—ã –æ–ø–µ—Ä–∞—Ü–∏–π 3D –º–∞—Ç—Ä–∏—Ü:

In [ ]:
x = np.ones((4, 1, 1))
y = np.random.randint(0, 5, size=(4, 3, 2))

print((x*y).shape)

(4, 3, 2)


In [ ]:
x = np.ones((3, 1))
y = np.random.randint(0, 5, size=(4, 3, 2))

print((x*y).shape)

(4, 3, 2)


In [ ]:
x = np.ones((1, 3, 2))
y = np.random.randint(0, 5, size=(5, 1, 2))

print((x*y).shape)

(5, 3, 2)


–í –ø–æ—Å–ª–µ–¥–Ω–∏—Ö –ø—Ä–∏–º–µ—Ä–∞—Ö –º–æ–∂–Ω–æ —É–≤–∏–¥–µ—Ç—å, —á—Ç–æ —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç–∏ –¥–æ–ª–∂–Ω—ã –±—ã—Ç—å —Å–æ–æ—Ç–Ω–æ—Å–∏–º—ã (–∫–æ–ª–∏—á–µ—Å—Ç–≤–∞ —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç–µ–π —Ä–∞–≤–Ω—ã). –í —Å–ª—É—á–∞–µ –Ω–µ—Ä–∞–≤–µ–Ω—Å—Ç–≤–∞ –∫–æ–ª–∏—á–µ—Å—Ç–≤–∞ —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç–µ–π –Ω–æ–≤—ã–µ —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç–∏ —Å–æ –∑–Ω–∞—á–µ–Ω–∏–µ–º 1 –¥–æ–±–∞–≤–ª—è—é—Ç—Å—è —Å–ª–µ–≤–∞ ($(3, 1) \rightarrow (1, 3, 1)$ –≤ –æ–¥–Ω–æ–º –∏–∑ –ø—Ä–∏–º–µ—Ä–æ–≤).

> –î–æ–±–∞–≤–ª–µ–Ω–∏–µ —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç–∏ –±—ã–ª–æ –∏ –≤ —Å–ª—É—á–∞–µ —É–º–Ω–æ–∂–µ–Ω–∏—è –≤–µ–∫—Ç–æ—Ä–∞ –Ω–∞ –º–∞—Ç—Ä–∏—Ü—É: $(4,)*(3, 4) \rightarrow (1, 4)*(3, 4)$

–ë—Ä–æ–∞–¥–∫–∞—Å—Ç–∏–Ω–≥ –¥–µ–ª–∞–µ—Ç—Å—è –ø–æ —Ç–µ–º –æ—Å—è–º, –∫–æ—Ç–æ—Ä—ã–µ —É –æ–¥–Ω–æ–≥–æ –æ–ø–µ—Ä–∞–Ω–¥–∞ –∏–º–µ—é—Ç —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç—å 1 –ø—É—Ç–µ–º –∫–æ–ø–∏—Ä–æ–≤–∞–Ω–∏—è.

> –í –Ω–∞—à–µ–º —Å–ª—É—á–∞–µ $(1, 4)*(3, 4) \rightarrow (3, 4)*(3, 4)$

–û—Å–æ–∑–Ω–∞—Ç—å –±—Ä–æ–∞–¥–∫–∞—Å—Ç–∏–Ω–≥ —Å—Ä–∞–∑—É –Ω–µ —Å–æ–≤—Å–µ–º –ø—Ä–æ—Å—Ç–æ, –Ω–æ –≥–ª–∞–≤–Ω–æ–µ –Ω–µ –∑–∞–±—ã–≤–∞—Ç—å, —á—Ç–æ —Ç–∞–∫–æ–π –∏–Ω—Å—Ç—Ä—É–º–µ–Ω—Ç –µ—Å—Ç—å –∏ –∏–º –Ω—É–∂–Ω–æ –ø–æ–ª—å–∑–æ–≤–∞—Ç—å—Å—è –≤–æ –∏–∑–±–µ–∂–∞–Ω–∏–µ –ª–∏—à–Ω–µ–≥–æ –∫–æ–¥–∞.

## –ò–∑–º–µ–Ω–µ–Ω–∏–µ —Ä–∞–∑–º–µ—Ä–æ–≤ –º–∞—Å—Å–∏–≤–∞ (Reshape)

–ï—â—ë –æ–¥–Ω–∞ –∏–Ω—Ç–µ—Ä–µ—Å–Ω–∞—è —Ç–µ–º–∞, –∫–æ—Ç–æ—Ä—É—é —Å—Ç–æ–∏—Ç —Ä–∞—Å—Å–º–æ—Ç—Ä–µ—Ç—å. –ú—ã —É–∂–µ –∫–∞—Å–∞–ª–∏—Å—å –≤–æ–ø—Ä–æ—Å–∞ –ø—Ä–∏–≤–µ–¥–µ–Ω–∏—è –º–∞—Å—Å–∏–≤–∞ –∫ –≤—ã–ø—Ä—è–º–ª–µ–Ω–Ω–æ–º—É –≤–∏–¥—É - —ç—Ç–æ –æ–¥–∏–Ω –∏–∑ –≤–∏–¥–æ–≤ –∏–∑–º–µ–Ω–µ–Ω–∏—è —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç–∏ –º–∞—Å—Å–∏–≤–∞.

–ü–æ —Å—É—Ç–∏, —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç—å –º–∞—Å—Å–∏–≤–∞ - —ç—Ç–æ –ø–æ—Ä—è–¥–æ–∫ –≤—ã—Å—Ç—Ä–æ–µ–Ω–Ω—ã—Ö —ç–ª–µ–º–µ–Ω—Ç—ã –≤ –Ω—ë–º. –ò–∑–º–µ–Ω–µ–Ω–∏–µ —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç–∏ - —ç—Ç–æ –∏–∑–º–µ–Ω–µ–Ω–∏–µ —Å—Ç—Ä—É–∫—Ç—É—Ä—ã **–±–µ–∑ –∏–∑–º–µ–Ω–µ–Ω–∏—è —ç–ª–µ–º–µ–Ω—Ç–æ–≤ –∏–ª–∏ –ø–æ—Ä—è–¥–∫–∞**.

–†–∞—Å—Å–º–æ—Ç—Ä–∏–º –Ω–∞ –ø—Ä–∏–º–µ—Ä–µ:

In [ ]:
arr = np.arange(20)
print(arr)

–í–æ—Ç –º—ã –∏–º–µ–µ–º –≤–µ–∫—Ç–æ—Ä –∏–∑ 20 —ç–ª–µ–º–µ–Ω—Ç–æ–≤ –≤ –ø–æ—Ä—è–¥–∫–µ –≤–æ–∑—Ä–∞—Å—Ç–∞–Ω–∏—è. –¢–µ–ø–µ—Ä—å, –¥–æ–ø—É—Å—Ç–∏–º, –Ω–∞–º –Ω—É–∂–Ω–æ —Å–¥–µ–ª–∞—Ç—å –º–∞—Å—Å–∏–≤ —Ä–∞–∑–º–µ—Ä–æ–º $(4, 5)$, –≤ –∫–æ—Ç–æ—Ä–æ–º –∫–∞–∂–¥—ã–π —Ä—è–¥ - —ç—Ç–æ –ø—Ä–æ–¥–æ–ª–∂–µ–Ω–∏–µ –ø—Ä–µ–¥—ã–¥—É—â–µ–≥–æ –ø–æ –≤–æ–∑—Ä–∞—Å—Ç–∞–Ω–∏—é —á–∏—Å–µ–ª. –î–ª—è –Ω–∞—á–∞–ª–∞ —Å–¥–µ–ª–∞–µ–º —Ä—É–∫–∞–º–∏:

In [ ]:
mtrx = np.ndarray((4, 5), dtype=np.int32)
mtrx[0, :] = arr[:5]
mtrx[1, :] = arr[5:10]
mtrx[2, :] = arr[10:15]
mtrx[3, :] = arr[15:]

print(mtrx)

–ü–æ–ª—É—á–∏–ª–æ—Å—å –∫–∞–∫ –Ω–∞–¥–æ, –Ω–æ –µ—Å—Ç—å –¥–≤–∞ –Ω–µ–¥–æ—Å—Ç–∞—Ç–∫–∞:
- –ï—Å–ª–∏ —ç–ª–µ–º–µ–Ω—Ç–æ–≤ –±—É–¥–µ—Ç –±–æ–ª—å—à–µ –∏ –Ω—É–∂–µ–Ω –±—É–¥–µ—Ç –¥—Ä—É–≥–æ–π —Ä–∞–∑–º–µ—Ä - –∫–æ–¥ –Ω–µ —É–Ω–∏–≤–µ—Ä—Å–∞–ª–µ–Ω;
- –ü—Ä–∏—Ö–æ–¥–∏—Ç—Å—è —Ä–∞—Å—Å—Ç–∞–≤–ª—è—Ç—å –¥–∞–Ω–Ω—ã–µ –≤—Ä—É—á–Ω—É—é.

–¢–µ–ø–µ—Ä—å –≤–∑–≥–ª—è–Ω–µ–º, –∫–∞–∫ —Ä–∞–±–æ—Ç–∞–µ—Ç –º–µ—Ç–æ–¥ `ndarray.reshape()`:

In [ ]:
print(arr.reshape((4, 5)))

–í —Ä–µ–∑—É–ª—å—Ç–∞—Ç–µ –ø—Ä–æ–∏—Å—Ö–æ–¥–∏—Ç —Ç–æ–∂–µ —Å–∞–º–æ–µ. –¢–æ –µ—Å—Ç—å, —ç–ª–µ–º–µ–Ω—Ç—ã —Ä–∞—Å–ø–æ–ª–æ–∂–∏–ª–∏—Å—å –≤ –ø–æ—Ä—è–¥–∫–µ —Ä–∞–∑–º–µ—â–µ–Ω–∏—è –ø–æ —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç—è–º: –Ω–∞—á–∏–Ω–∞—è —Å –ø–µ—Ä–≤–æ–π —Å—Ç—Ä–æ–∫–∏ (–Ω—É–ª–µ–≤–∞—è —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç—å) –∑–∞–ø–æ–ª–Ω—è–µ—Ç—Å—è –ø–æ –∫–æ–ª–æ–Ω–∫–∞–º (–ø–µ—Ä–≤–∞—è —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç—å), –∞ –∫–∞–∫ —Ç–æ–ª—å–∫–æ –∑–∞–ø–æ–ª–Ω–µ–Ω–∏–µ –ø–æ –∫–æ–ª–æ–Ω–∫–∞–º –∑–∞–∫–æ–Ω—á–µ–Ω–æ - –ø–µ—Ä–µ—Ö–æ–¥–∏–º –Ω–∞ —Å–ª–µ–¥—É—é—â–∏–π —Ä—è–¥.

–¢–∞–∫–∏–º –æ–±—Ä–∞–∑–æ–º, –≤ –∫–∞–∫—É—é –±—ã —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç—å –Ω–µ –ø—Ä–æ–∏—Å—Ö–æ–¥–∏–ª–æ –∏–∑–º–µ–Ω–µ–Ω–∏–µ —Ä–∞–∑–º–µ—Ä–∞ - —Ä–∞—Å–ø–æ–ª–æ–∂–µ–Ω–∏–µ –±—É–¥–µ—Ç –ø—Ä–∏–¥–µ—Ä–∂–∏–≤–∞—Ç—å—Å—è —ç—Ç–æ–≥–æ –ø—Ä–∞–≤–∏–ª–∞.

–î–ª—è –ª—É—á—à–µ–≥–æ –ø–æ–Ω–∏–º–∞–Ω–∏—è –ø–æ—Å–º–æ—Ç—Ä–∏–º –Ω–∞ –¥—Ä—É–≥–∏–µ –ø—Ä–µ–¥—Å—Ç–∞–≤–ª–µ–Ω–∏—è:

In [ ]:
print(arr.reshape((2, 10)))
print(arr.reshape((5, 4)))
print(arr.reshape((20, 1)))

–¢–∞–∫–∏–º –æ–±—Ä–∞–∑–æ–º, –º–æ–∂–Ω–æ –ø—Ä–∏–≤–æ–¥–∏—Ç—å –∫ –ª—é–±–æ–π —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç–∏ —Å —É—á–µ—Ç–æ–º –ø—Ä–∞–≤–∏–ª–∞:
> –ö–æ–ª–∏—á–µ—Å—Ç–≤–æ —ç–ª–µ–º–µ–Ω—Ç–æ–≤ –¥–æ–ª–∂–Ω–æ —Å–æ—Ö—Ä–∞–Ω—è—Ç—å—Å—è

–ù–æ –±—ã–≤–∞—é—Ç —Å–∏—Ç—É–∞—Ü–∏–∏, –∫–æ–≥–¥–∞ –º—ã —Ç–æ—á–Ω–æ –Ω–µ –∑–Ω–∞–µ–º –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —ç–ª–µ–º–µ–Ω—Ç–æ–≤, –Ω–æ –Ω–∞–º –Ω—É–∂–Ω–æ —Ç–æ—á–Ω–æ —Å–æ–∑–¥–∞—Ç—å, –Ω–∞–ø—Ä–∏–º–µ—Ä, 4 —Å—Ç—Ä–æ–∫–∏ –≤ –º–∞—Ç—Ä–∏—Ü–µ. –í —ç—Ç–æ–º –ø–æ–º–æ–∂–µ—Ç –Ω–µ–æ–ø—Ä–µ–¥–µ–ª–µ–Ω–Ω–∞—è —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç—å, –∫–æ—Ç–æ—Ä–∞—è –∑–∞–¥–∞–µ—Ç—Å—è —á–∏—Å–ª–æ–º -1:

In [ ]:
print(arr.reshape((4, -1)))

–¢–∞–∫–∏–º –æ–±—Ä–∞–∑–æ–º –º–æ–∂–Ω–æ –∑–∞–¥–∞—Ç—å, —á—Ç–æ –º–∞—Ç—Ä–∏—Ü–∞ –¥–æ–ª–∂–Ω–∞ –±—ã—Ç—å 2D —Å —Ñ–∏–∫—Å–∏—Ä–æ–≤–∞–Ω–Ω—ã–º –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ–º —Å—Ç—Ä–æ–∫, –Ω–æ –±–µ–∑ —Ñ–∏–∫—Å–∞—Ü–∏–∏ –Ω–∞ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Å—Ç–æ–ª–±—Ü–æ–≤. –ö–æ–Ω–µ—á–Ω–æ –∂–µ, –µ—Å–ª–∏ –≤ –∏—Å—Ö–æ–¥–Ω–æ–º –±—É–¥–µ—Ç 21 —ç–ª–µ–º–µ–Ω—Ç, —Ç–æ —Ç–∞–∫–æ–π —Ç—Ä—é–∫ –Ω–µ —Å—Ä–∞–±–æ—Ç–∞–µ—Ç, –ø–æ—Ç–æ–º—É —á—Ç–æ 21 –Ω–µ –¥–µ–ª–∏—Ç—Å—è –Ω–∞ 4 –±–µ–∑ –æ—Å—Ç–∞—Ç–∫–∞.

## –û–±—ä–µ–¥–∏–Ω–µ–Ω–∏–µ –º–∞—Å—Å–∏–≤–æ–≤

–ü—Ä–∏ —Ä–∞–±–æ—Ç–µ —Å –º–∞—Å—Å–∏–≤–∞–º–∏ –±—ã–≤–∞—é—Ç —Å–ª—É—á–∞–∏, –∫–æ–≥–¥–∞ –Ω–µ—Å–∫–æ–ª—å–∫–æ –º–∞—Å—Å–∏–≤–æ–≤ –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –æ–±—ä–µ–¥–∏–Ω–∏—Ç—å –≤ –æ–¥–∏–Ω. –î–ª—è —ç—Ç–æ–≥–æ –ø–æ–º–æ–∂–µ—Ç —Ñ—É–Ω–∫—Ü–∏—è `np.concatenate()` –∏ –ø–æ–Ω–∏–º–∞–Ω–∏–µ –µ–µ –æ—Å–Ω–æ–≤–Ω—ã—Ö –ø—Ä–∞–≤–∏–ª.

In [ ]:
x = np.arange(10).reshape((2, 5))
y = np.arange(15).reshape((3, 5))

print(x)
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


–î–ª—è –æ–±—ä–µ–¥–∏–Ω–µ–Ω–∏—è –º–∞—Å—Å–∏–≤–æ–≤ –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ, —á—Ç–æ–±—ã –æ–¥–Ω–∞ –∏–∑ —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç–µ–π –∏–º–µ–ª–∞ –æ–¥–∏–Ω–∞–∫–æ–≤–æ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —ç–ª–µ–º–µ–Ω—Ç–æ–≤. –≠—Ç–æ –¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ –ª–æ–≥–∏—á–Ω–æ–µ —Ç—Ä–µ–±–æ–≤–∞–Ω–∏–µ –∑–∞–¥–∞—ë—Ç—Å—è –∞—Ä–≥—É–º–µ–Ω—Ç–æ–º `axis` –≤ —Ñ—É–Ω–∫—Ü–∏–∏. –î–ª—è –∑–∞–ø–æ–º–∏–Ω–∞–Ω–∏—è –Ω–∞–ø—Ä–∞–≤–ª–µ–Ω–∏—è –ª–∏–Ω–∏–∏ —Å–æ–µ–¥–∏–Ω–µ–Ω–∏—è –∏ –æ–ø–∏—Å—ã–∞–≤–µ—Ç—Å—è —á–∏—Å–ª–æ–º - "0"-—Å—Ç—Ä–æ–∫–∞, "1" - —Å—Ç–æ–ª–±–µ—Ü.

In [ ]:
print(np.concatenate((x, y), axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


–û–±—Ä–∞—Ç–∏—Ç–µ –≤–Ω–∏–º–∞–Ω–∏–µ, —á—Ç–æ –º–∞—Å—Å–∏–≤—ã –ø–µ—Ä–µ–¥–∞—é—Ç—Å—è –≤ –≤–∏–¥–µ –∫–æ—Ä—Ç–µ–∂–∞, —á—Ç–æ –ø–æ–∑–≤–æ–ª—è–µ—Ç –æ–±—ä–µ–¥–∏–Ω—è—Ç—å –¥–≤–∞ –∏ –±–æ–ª–µ–µ –º–∞—Å—Å–∏–≤–æ–≤.

### –ó–∞–¥–∞–Ω–∏–µ - –æ–±—ä–µ–¥–∏–Ω—è–µ–º

–û–±—ä–µ–¥–∏–Ω–∏—Ç–µ —Ç—Ä–∏ –º–∞—Å—Å–∏–≤–∞ –≤–¥–æ–ª—å –∫–æ–ª–æ–Ω–æ–∫:

In [ ]:
import numpy as np

x = np.arange(9).reshape((3, 3))
y = np.arange(12).reshape((3, 4))
z = np.arange(15).reshape((3, 5))

result = np.concatenate((x, y, z), axis=1)
print(result)

[[ 0  1  2  0  1  2  3  0  1  2  3  4]
 [ 3  4  5  4  5  6  7  5  6  7  8  9]
 [ 6  7  8  8  9 10 11 10 11 12 13 14]]


### –ó–∞–¥–∞–Ω–∏–µ - —Ä–∞—Å—à–∏—Ä—è–µ–º

–ù–∞–ø–∏—à–∏—Ç–µ —Ä–µ–∞–ª–∏–∑–∞—Ü–∏—é –¥–æ–±–∞–≤–ª–µ–Ω–∏—è —Å—Ç–æ–±—Ü–∞ –µ–¥–∏–Ω–∏—Ü –∫ –º–∞—Ç—Ä–∏—Ü–µ —Å–ª–µ–≤–∞:

In [ ]:
import numpy as np

x = np.arange(1, 10).reshape((3, 3))
ones_column = np.ones((x.shape[0], 1))

result = np.concatenate((ones_column, x), axis=1)
print(result)

[[1. 1. 2. 3.]
 [1. 4. 5. 6.]
 [1. 7. 8. 9.]]


## –°–æ—Ä—Ç–∏—Ä–æ–≤–∫–∞ –º–∞—Å—Å–∏–≤–∞

Numpy –∫–∞–∫ —Å–µ—Ä—å—ë–∑–Ω–∞—è –±–∏–±–ª–∏–æ—Ç–µ–∫–∞ —Ä–∞–±–æ—Ç—ã —Å –º–∞—Å—Å–∏–≤–∞–º–∏ –∏–º–µ–µ—Ç —Ç–∞–∫–∂–µ –∏ —Ñ—É–Ω–∫—Ü–∏–æ–Ω–∞–ª —Å–æ—Ä—Ç–∏—Ä–æ–≤–∫–∏. –î–ª—è —ç—Ç–æ–≥–æ –µ—Å—Ç—å —Ñ—É–Ω–∫—Ü–∏—è `np.sort()`, –∫–æ—Ç–æ—Ä–∞—è –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç —Å–æ—Ä—Ç–∏—Ä–æ–≤–∫—É —ç–ª–µ–º–µ–Ω—Ç–æ–≤ –∏ –≤–æ–∑–≤—Ä–∞—â–∞–µ—Ç –æ—Ç—Å–æ—Ä—Ç–∏—Ä–æ–≤–∞–Ω–Ω—ã–π –º–∞—Å—Å–∏–≤:

In [ ]:
unsorted_arr = np.array([2, 4, 5, 1, 2, 7, 5, 0, -1, 3, 5])
sorted_arr = np.sort(unsorted_arr)

print(unsorted_arr)
print(sorted_arr)

[ 2  4  5  1  2  7  5  0 -1  3  5]
[-1  0  1  2  2  3  4  5  5  5  7]


–ü–æ–º–∏–º–æ —è–≤–Ω–æ–π —Å–æ—Ä—Ç–∏—Ä–æ–≤–∫–∏ —Å—É—â–µ—Å—Ç–≤—É–µ—Ç —Ç–∞–∫–∂–µ —Ñ—É–Ω–∫—Ü–∏—è `np.argsort()`, –∫–æ—Ç–æ—Ä–∞—è –≤–æ–∑–≤—Ä–∞—â–∞–µ—Ç –Ω–µ –æ—Ç—Å–æ—Ä—Ç–∏—Ä–æ–≤–∞–Ω–Ω—ã–π –º–∞—Å—Å–∏–≤, –∞ –º–∞—Å—Å–∏–≤ –∏–Ω–¥–µ–∫—Å–æ–≤ –∏—Å—Ö–æ–¥–Ω–æ–≥–æ –º–∞—Å—Å–∏–≤–∞ –≤ –ø–æ—Ä—è–¥–∫–µ, –∫–æ—Ç–æ—Ä—ã–π –¥–∞—ë—Ç –æ—Ç—Å–æ—Ä—Ç–∏—Ä–æ–≤–∞–Ω–Ω—ã–π –∏—Å—Ö–æ–¥–Ω—ã–π. –ü–æ—Å–º–æ—Ç—Ä–∏–º:

In [ ]:
sorted_indices = np.argsort(unsorted_arr)
print(sorted_indices)

# –ê —Ç–µ–ø–µ—Ä—å –≤–æ—Å–ø–æ–ª—å–∑—É–µ–º—Å—è –∏–Ω–¥–µ–∫—Å–∞–º–∏ –∏ –æ—Ç–æ–±—Ä–∞–∑–∏–º –∏—Å—Ö–æ–¥–Ω—ã–π –º–∞—Å—Å–∏–≤ —Å –∏–Ω–¥–µ–∫—Å–∞—Ü–∏–µ–π
print(unsorted_arr[sorted_indices])

[ 8  7  3  0  4  9  1  2  6 10  5]
[-1  0  1  2  2  3  4  5  5  5  7]


### –ó–∞–¥–∞–Ω–∏–µ - –ø–æ–∫–æ–ø–∞–µ–º—Å—è –≤ –¥–æ–∫–∞—Ö

–ü–æ —Ç–∞–∫–æ–º—É –∂–µ –ø—Ä–∏–Ω—Ü–∏–ø—É –∏–º–µ–Ω–æ–≤–∞–Ω–∏—è –Ω–∞–π–¥–∏—Ç–µ —Ñ—É–Ω–∫—Ü–∏—é –≤ –¥–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏–∏, –∫–æ—Ç–æ—Ä–∞—è –≤–æ–∑–≤—Ä–∞—â–∞–µ—Ç –∏–Ω–¥–µ–∫—Å –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–≥–æ/–º–∏–Ω–∏–º–∞–ª—å–Ω–æ–≥–æ (–≤ –∑–∞–≤–∏–º–æ—Å—Ç–∏ –æ—Ç –≤–∞—Ä–∏–∞–Ω—Ç–∞) —ç–ª–µ–º–µ–Ω—Ç–∞ –≤ –º–∞—Å—Å–∏–≤–µ.

–í–æ—Å–ø–æ–ª—å–∑—É–π—Ç–µ—Å—å –Ω–∞–π–¥–µ–Ω–Ω–æ–π —Ñ—É–Ω–∫—Ü–∏–µ–π –∏ –Ω–∞–π–¥–∏—Ç–µ –∏–Ω–¥–µ–∫—Å—ã –º–∞–∫—Å–∏–º–∞–ª—å–Ω—ã—Ö —ç–ª–µ–º–µ–Ω—Ç–æ–≤ –≤ –∫–∞–∂–¥–æ–º —Å—Ç–æ–ª–±—Ü–µ 2D –º–∞—Ç—Ä–∏—Ü—ã:

In [ ]:
import numpy as np

arr = np.array([
    [11, -1, 1, 3, 5],
    [6, 1, 0, -1, 10],
    [1, 3, 2, 3, 6],
    [5, 2, 7, 8, 9],
])

max_indices = np.argmax(arr, axis=0)
min_indices = np.argmin(arr, axis=0)

print("–ú–∞–∫—Å–∏–º–∞–ª—å–Ω—ã–µ –∏–Ω–¥–µ–∫—Å—ã:", max_indices)
print("–ú–∏–Ω–∏–º–∞–ª—å–Ω—ã–µ –∏–Ω–¥–µ–∫—Å—ã:", min_indices)


–ú–∞–∫—Å–∏–º–∞–ª—å–Ω—ã–µ –∏–Ω–¥–µ–∫—Å—ã: [0 2 3 3 1]
–ú–∏–Ω–∏–º–∞–ª—å–Ω—ã–µ –∏–Ω–¥–µ–∫—Å—ã: [2 0 1 1 0]


### –ó–∞–¥–∞–Ω–∏–µ - –Ω–∏–∫—É–¥–∞ –±–µ–∑ —Å–æ—Ä—Ç–∏—Ä–æ–≤–∫–∏

–ù–∞–ø–∏—à–∏—Ç–µ –∫–æ–¥ —Å–æ—Ä—Ç–∏—Ä–æ–≤–∫–∏ –º–∞—Å—Å–∏–≤–∞ –ø–æ —Å—Ç–æ–ª–±—Ü–∞–º:

In [ ]:
import numpy as np

arr = np.array([
    [11, 2, 1, 3, 5],
    [6, 2, 0, -1, 10],
    [1, 3, 2, 3, 5],
    [5, 2, 7, 8, 9],
])

sorted_arr = np.sort(arr, axis=0)

print(sorted_arr)


[[ 1  2  0 -1  5]
 [ 5  2  1  3  5]
 [ 6  2  2  3  9]
 [11  3  7  8 10]]


## –ó–∞–¥–∞—á–∫–∏

–°–æ–∑–¥–∞–π—Ç–µ –º–∞—Å—Å–∏–≤, —Å–æ—Å—Ç–æ—è—â–∏–π –∏–∑ —Å–ª—É—á–∞–π–Ω—ã—Ö —ç–ª–µ–º–µ–Ω—Ç–æ–≤ –≤ –¥–∏–∞–ø–∞–∑–æ–Ω–µ $[-10; 20]$ —Ä–∞–∑–º–µ—Ä–æ–º $(5, 7)$:

In [ ]:
import numpy as np

arr = np.random.randint(-10, 20, size=(5, 7))

print(arr)

[[ 12  10  -2  13  10  10 -10]
 [ -1  -3  -8   2  -8  -6   3]
 [  6  18  11  -2   8  -9  15]
 [  5  19   1  10   9  18   0]
 [ -7   8  -5  12  17  -4 -10]]


–î–æ–±–∞–≤—å—Ç–µ –≥—Ä–∞–Ω–∏—Ü—É –≤ –≤–∏–¥–µ –Ω—É–ª–µ–π —Å–æ –≤—Å–µ—Ö —Å—Ç–æ—Ä–æ–Ω 2D –º–∞—Å—Å–∏–≤–∞:

In [ ]:
import numpy as np

data = np.arange(1, 16).reshape((3, 5))

padded_data = np.pad(data, pad_width=1, constant_values=0)

print(padded_data)

[[ 0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  0]
 [ 0  6  7  8  9 10  0]
 [ 0 11 12 13 14 15  0]
 [ 0  0  0  0  0  0  0]]


–†–∞–∑–±–µ—Ä–∏—Ç–µ—Å—å —Å —Ñ—É–Ω–∫—Ü–∏–µ–π `np.clip()` –∏ –ø—Ä–æ–∏–∑–≤–µ–¥–∏—Ç–µ –æ–≥—Ä–∞–Ω–∏—á–µ–Ω–∏–µ –º–∞—Å—Å–∏–≤–∞, —á—Ç–æ–±—ã –≤ –Ω–µ–º –∑–Ω–∞—á–µ–Ω–∏—è –±—ã–ª–∏ –Ω–µ –±–æ–ª–µ–µ —à–µ—Å—Ç–∏ –∏ –Ω–µ –º–µ–Ω–µ–µ –¥–≤—É—Ö:

In [ ]:
import numpy as np

data = np.arange(1, 16).reshape((3, 5))

clipped_data = np.clip(data, 2, 6)

print(clipped_data)


[[2 2 3 4 5]
 [6 6 6 6 6]
 [6 6 6 6 6]]


–ü—Ä–æ–∏–∑–≤–µ–¥–∏—Ç–µ –º–æ–¥–∏—Ñ–∏–∫–∞—Ü–∏—é –º–∞—Å—Å–∏–≤–∞ —Ç–∞–∫, —á—Ç–æ–±—ã –∑–Ω–∞—á–µ–Ω–∏–µ –≤ –∫–æ–ª–æ–Ω–∫–µ —Ä–µ–∑—É–ª—å—Ç–∞—Ç–∞ —Å–æ–æ—Ç–≤–µ—Ç—Å—Ç–≤–æ–≤–∞–ª–æ –∏—Å—Ö–æ–¥–Ω–æ–º—É –∑–Ω–∞—á–µ–Ω–∏—é, –≤–æ–∑–≤–µ–¥–µ–Ω–Ω–æ–º—É –≤ —Å—Ç–µ–ø–µ–Ω—å –∏–Ω–¥–µ–∫—Å–∞ –∫–æ–ª–æ–Ω–∫–∏:

In [ ]:
import numpy as np

data = np.full((3, 5), fill_value=2, dtype=np.int32)

modified_data = np.power(data, np.arange(5))

print(modified_data)


[[ 1  2  4  8 16]
 [ 1  2  4  8 16]
 [ 1  2  4  8 16]]


–£–º–Ω–æ–∂—å—Ç–µ –∫–∞–∂–¥—É—é –∫–æ–ª–æ–Ω–∫—É –Ω–∞ –µ—ë –∏–Ω–¥–µ–∫—Å:

In [ ]:
import numpy as np

data = np.full((3, 5), fill_value=2, dtype=np.int32)

modified_data = np.multiply(data, np.arange(5))

print(modified_data)


[[0 2 4 6 8]
 [0 2 4 6 8]
 [0 2 4 6 8]]


–£–º–Ω–æ–∂—å—Ç–µ –∫–∞–∂–¥—ã–π —á—ë—Ç–Ω—ã–π —Ä—è–¥ –≤ –º–∞—Ç—Ä–∏—Ü–µ –Ω–∞ –≤–µ–∫—Ç–æ—Ä:

In [ ]:
import numpy as np

data = np.repeat(np.arange(1, 8), 4).reshape(7, 4)
vec = np.array([1, 2, 1, 2])

modified_data = data.copy()

modified_data[::2] = np.multiply(modified_data[::2], vec)

print(modified_data)

[[ 1  2  1  2]
 [ 2  2  2  2]
 [ 3  6  3  6]
 [ 4  4  4  4]
 [ 5 10  5 10]
 [ 6  6  6  6]
 [ 7 14  7 14]]


–û–ø—Ä–µ–¥–µ–ª–∏—Ç–µ –∏–Ω–¥–µ–∫—Å—ã –¥–≤—É—Ö –Ω–∞–∏–±–æ–ª—å—à–∏—Ö —ç–ª–µ–º–µ–Ω—Ç–æ–≤ –≤ –º–∞—Ç—Ä–∏—Ü–µ –ø–æ –∫–∞–∂–¥–æ–º—É —Ä—è–¥—É:

In [ ]:
import numpy as np

data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 4, 24, 24, 28,  3, 40]])

max_indices = np.argsort(-data, axis=1)[:, :2]
print(max_indices)


[[4 1]
 [1 2]
 [3 1]
 [5 3]]


–í—ã–±–µ—Ä–∏—Ç–µ –¥–≤–µ —Å–ª—É—á–∞–π–Ω—ã–µ –∫–æ–ª–æ–Ω–∫–∏ –∏–∑ –º–∞—Å—Å–∏–≤–∞:

<details><summary>–ü–æ–¥—Å–∫–∞–∑–∫–∞ 1</summary>
–î–ª—è —Å–ª—É—á–∞–π–Ω–æ–≥–æ –≤—ã–±–æ—Ä–∞ –ø–æ–ª–µ–∑–Ω–æ –≤–æ—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å—Å—è —Ñ—É–Ω–∫—Ü–∏–µ–π `np.random.choice()`
</details>

<details>
<summary>–ü–æ–¥—Å–∫–∞–∑–∫–∞ 2</summary>
`np.random.choice()` –ø—Ä–∏–Ω–∏–º–∞–µ—Ç –Ω–∞ –≤—Ö–æ–¥ 1D –º–∞—Å—Å–∏–≤, —Ç–∞–∫ —á—Ç–æ –¥–ª—è –≤—ã–±–æ—Ä–∞ –º–æ–∂–Ω–æ —Å–æ–∑–¥–∞—Ç—å –º–∞—Å—Å–∏–≤ –∏–Ω–¥–µ–∫—Å–æ–≤ –∫–æ–ª–æ–Ω–æ–∫ (`range()` —Å –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ–º –∫–æ–ª–æ–Ω–æ–∫) –∏ –∏–∑ –Ω–µ–≥–æ —Ñ—É–Ω–∫—Ü–∏—è –≤—ã–±–µ—Ä–µ—Ç –¥–≤–∞ —Å–ª—É—á–∞–π–Ω—ã—Ö –∏–Ω–¥–µ–∫—Å–∞
</details>

In [ ]:
import numpy as np

data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 4, 24, 24, 28,  3, 40]])

random_columns = np.random.choice(data.shape[1], size=2, replace=False)

selected_columns = data[:, random_columns]

print(selected_columns)


[[20  8]
 [ 7 15]
 [ 8  9]
 [ 4 40]]


–°–æ–∑–¥–∞–π—Ç–µ –º–∞—Å—Å–∏–≤ —Ä–∞–∑–º–µ—Ä–æ–º $(10, 3)$, –∫–æ—Ç–æ—Ä—ã–π —Å–æ—Å—Ç–æ–∏—Ç –∏–∑ –ø–æ–≤—Ç–æ—Ä—è—é—â–∏—Ö—Å—è —Ä—è–¥–æ–≤ –∏—Å—Ö–æ–¥–Ω–æ–≥–æ –º–∞—Å—Å–∏–≤–∞:

In [2]:
import numpy as np

data = np.arange(9).reshape(3, 3)
repeated_rows = np.tile(data, (4, 1))[:10, :]

print(repeated_rows)


[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]]


–°–æ–±–µ—Ä–∏—Ç–µ –º–∞—Å—Å–∏–≤, —Å–æ—Å—Ç–æ—è—â–∏–π –∏–∑ —ç–ª–µ–º–µ–Ω—Ç–æ–≤ 2-–π –∏ 4-–π –∫–æ–ª–æ–Ω–æ–∫ –∏ —Å—Ç—Ä–æ–∫ —Å 1-–π –ø–æ 3-—é (**—Ü–∏—Ñ—Ä—ã —É–∫–∞–∑–∞–Ω—ã —Å —É—á—ë—Ç–æ–º –∏–Ω–¥–µ–∫—Å–∞—Ü–∏–∏ —Å 0-–ª—è!**):

In [13]:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 14, 9,  33, 21,  7,  6],
                [ 4, 24, 24, 28,  3, 40]])


arr[0,0]=data[1,2]
arr[0,1]=data[1,4]
arr[1,0]=data[2,2]
arr[1,1]=data[2,4]
arr[2,0]=data[3,2]
arr[2,1]=data[3,4]
print (arr)


[[23 22]
 [ 9  0]
 [33  7]]


–ò–Ω–≤–µ—Ä—Ç–∏—Ä—É–π—Ç–µ –ø–æ—Ä—è–¥–æ–∫ —ç–ª–µ–º–µ–Ω—Ç–æ–≤ –≤ –ø–æ—Å–ª–µ–¥–Ω–∏—Ö –¥–≤—É—Ö –∫–æ–ª–æ–Ω–∫–∞—Ö:

In [14]:
data = np.array([[20, 22,  2, 14, 25,  8],
                [ 7, 25, 23,  3, 22, 15],
                [ 8, 16,  9, 22,  0,  9],
                [ 14, 9,  33, 21,  7,  6],
                [ 4, 24, 24, 28,  3, 40]])

arr=data.copy()
mas = data[::-1]
arr[:,4:6]=mas[:,4:6]
print(arr)


[[20 22  2 14  3 40]
 [ 7 25 23  3  7  6]
 [ 8 16  9 22  0  9]
 [14  9 33 21 22 15]
 [ 4 24 24 28 25  8]]


## –ü–æ–ª–µ–∑–Ω—ã–µ —Å—Å—ã–ª–∫–∏
* [More than 15 jupyter notebooks to learn Numpy](https://www.kaggle.com/getting-started/115421)
